FROM node:18.14.2

WORKDIR /usr/src/app

# 전역으로 @nestjs/cli 설치
RUN npm install -g @nestjs/cli

# 의존성 파일을 먼저 복사하여 캐시 활용
COPY package*.json ./

# 의존성 설치
RUN npm install

# 불필요한 타입 패키지 제거
RUN npm uninstall @types/cron

# 애플리케이션 소스 코드 복사
COPY . .

# NestJS 애플리케이션 실행
CMD ["nest", "start", "user", "--watch"]
