FROM node:18.14.2
WORKDIR /usr/src/app

# Copy package.json and install dependencies first
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application
RUN npm run build

# Run the NestJS app in watch mode
CMD ["npm", "run", "start:dev"]
